---
title: "maths"
author: "Emma Govan"
date: "24/03/23"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(tidyverse)
library(R2jags)
library(ggplot2)
library(gtools)
library(LaplacesDemon)

set.seed(123)
```

## Introduction

This file contains the maths and code for running a simple stable isotope mixing model model through a Fixed Form Variational Bayes (FFVB) algorithm. The text below introduces the model, outlines the algorithm, fits the model using MCMC (via JAGS) and then fits the FFVB algorithm. Finally the two approaches are compared using plots of the derived posterior distributions. 

## Model

We use the likelihood:

$$y_{i} \sim N(\frac{\sum_{k=1}^Kp_kq_k(\mu_c+\mu_{k})}{\sum_{k=1}^Kp_kq_k},\frac{\sum_{k=1}^Kp_k^2q_{k}^2(\sigma^2_c+\sigma^2_{k})}{\sum_{k=1}^Kp_k^2q_{k}^2} + \tau^{-1})$$


where $y$ is the data and $p$ and $\tau$ are the parameters to be estimated. 

We use the following prior distributions for $p$ and $\tau$:

$$p = \frac{\exp{f}}{\sum\exp{f}}$$

$\tau \sim Ga(c, d)$

$$\pi(f) \sim mvn(\mu_f, \Sigma_f)$$

$$\pi(\tau) = \frac{d^c}{\Gamma(c)} \tau_j^{c-1} \exp(-d\tau_j)$$
Here $\mu_f, \Sigma_f, c$, and $d$ are all fixed.

## Fixed Form Variational Inference

The algorithm detailed below comes from Algorithm 4 [here](https://vbayeslab.github.io/VBLabDocs/tutorial/ffvb).

If we define the joint set of parameters as $\theta = (f, \tau)$ then we write the factorised variational posterior as:

$$q_\lambda(\theta) = q(f)q(\tau)$$

where $\lambda = (\mu_f, \Sigma_f, c,d)^T$ is the set of hyper-parameters associated with the variational posteriors:

$$q(f) \equiv mvn(\mu_f, \Sigma_f)$$

$$q(\tau) \equiv Ga(c_{\sigma}, d_{\sigma})$$

We use parenthetical super-scripts to denote iterations. To start the algorithm, initial values are required for $\lambda^{(0)}$, the sample size $S$, the adaptive learning weights ($\beta_1, \beta_2$), the fixed learning rate $\epsilon_0$, the threshold $\tau$, the rolling window size $t_W$ and the maximum patience $P$. 

Define $h$ to be the log of the joint distribution up to the constant of proportionality:

$$h(\theta) = \log \left( p(y|\theta) p(\theta) \right)$$
and $h_\lambda$ to be the log of the ratio between the joint and the VB posterior:

$$h_\lambda(\theta) = \log \left( \frac{ p(y|\theta) p(\theta) }{ q_\lambda(\theta) } \right) = h(\theta) - \log q_\lambda(\theta) $$


The initialisation stage proceeds with:

1. Generate samples from $\theta_s \sim q_{\lambda^{(0)}(\theta)}$ for $s=1,...S$
2. Compute the unbiased estimate of the lower bound gradient:
$$\widehat{\nabla_\lambda{LB}(\lambda^{(0)})} = \frac{1}{S}\sum_{s=1}^S\nabla_\lambda[\log(q_\lambda(\theta_s))] \circ h_\lambda(\theta_s) \bigg\rvert_{\lambda = \lambda^{(0)}}$$
where $\circ$ indicates elementwise multiplication
3. Set $\bar{g}_0 := \nabla_\lambda{LB}(\lambda^{(0)})$, $\bar{\nu_0} := \bar{g_0}^2$, $\bar{g} = g_0$, $\bar{\nu} = \nu_0$
4. Estimate the control variate $c_i$ for the $i$th element of $\lambda$ as:
$$c_i = \frac{Cov \left(\nabla_{\lambda_i}[\log(q_\lambda(\theta))]h_\lambda(\theta),\nabla_{\lambda_i}[\log(q_\lambda(\theta))]\right)}{ Var(\nabla_{\lambda_i}[\log(q_\lambda(\theta))])}$$

across the samples generated in step 1
5. Set $t=1$, patience = 0, and `stop = FALSE`

Now the algorithm runs with:

1. Generate samples from $\theta_s \sim q_{\lambda^{(t)}(\theta)}$ for $s=1,...S$
2. Compute the unbiased estimate of the lower bound gradient:
$$g_t := \widehat{\nabla_\lambda{LB}(\lambda^{(t)})} = \frac{1}{S}\sum_{s=1}^S\nabla_\lambda[\log(q_\lambda(\theta_s))] \circ(h_\lambda(\theta_s) - c) \bigg\rvert_{\lambda = \lambda^{(t)}}$$


where $\circ$ indicates elementwise multiplication.
3. Estimate the new control variate $c_i$ for the $i$th element of $\lambda$ as:
$$c_i = \frac{Cov \left(\nabla_{\lambda_i}[\log(q_\lambda(\theta))]h_\lambda(\theta),\nabla_{\lambda_i}[\log(q_\lambda(\theta))]\right)}{ Var(\nabla_{\lambda_i}[\log(q_\lambda(\theta))])}$$
across the samples generated in step 1
4. Compute: 
\begin{eqnarray}
v_t &=& g_t^2 \\
\bar{g} &=& \beta_1\bar{g} + (1-\beta_1)g_t \\
\bar{v} &=& \beta_2\bar{v} + (1-\beta_2)v_t \\
\end{eqnarray}
5. Update the learning rate:
$l_t = min(\epsilon_0, \epsilon_0\frac{\tau}{t})$
and the variational hyper-parameters:
$$\lambda^{(t+1)} = \lambda^{(t)} + l_t\frac{\bar{g}}{\sqrt{\bar{v}}}$$

6. Compute the lower bound estimate:
$$\widehat{LB}(\lambda^{(t)}) := \frac{1}{S} \sum_{s=1}^S h_{\lambda^{(t)}}(\theta_s)$$
7. If $t \ge t_W$ compute the moving average LB
$$\overline{LB}_{t-t_W+1} := \frac{1}{t_W} \sum_{k=1}^{t_W} \widehat{LB}(\lambda^{(t-k + 1)})$$
If $\overline{LB}_{t-t_W+1} \ge \max(\bar{LB})$ patience = 0, else patience = patience +1
8. If patience $\ge$ P, `stop = TRUE`
9. Set $t:=t+1$

